README.md

fix a typo in readme canUseDom

---

README.md
package.json
src/Portal.js

https://github.com/react-component/trigger/pull/69
用来代替原有的 `getContainerRenderMixin`

Add a Portal component

---

README.md
package.json
src/getContainerRenderMixin.jsx

ref: https://github.com/react-component/trigger/pull/76

feat: support forceRender

---

package.json
src/debug/diff.js
tests/debug.test.js
tests/index.test.js

* import `createReactClass` in `--save-dev` to fix test case
* Add `debug/diff` to helps the jest test check usage (refactor purpose).

fix test & add debug function

---

src/debug/diff.js
tests/debug.test.js

Support format toString for debug

Extend debug diff method

---

package.json
src/PortalWrapper.js
src/getScrollBarSize.js
src/switchScrollingEffect.js

https://github.com/ant-design/ant-design/issues/17323
1. 解决 modal 和 drawer 同时存在时， body 的滚动处理冲突，提取 protalWrapper 同时给两个组件使用
2. 滚动条宽度的获取和定义隐藏滚动条时对 body 的处理，用 width, padding 会对 absolute 的造成闪动。

add protal wrapper and getScroll func

---

src/Portal.js

https://github.com/ant-design/ant-design/issues/17886

fix portal container

---

.circleci/config.yml
src/warning.ts
tests/warning.test.js

due to https://github.com/ant-design/ant-design/blob/master/components/_util/warning.tsx#L5

feat: add reset warned vars

---

package.json
src/warning.ts
tests/index.test.js
tests/warning.test.js

Get yellow note:
```jsx
import { noteOnce } from '../src/warning';
noteOnce(false, 'a message...'); // 'Note: a meesage...'
```

feat: support `noteOnce`

---

src/test/domHook.ts
tests/domHook.test.js

Support mock dom props in jest env.

feat: Add test utils

---

package.json

Resolve the problem that related to this issue
https://github.com/react-component/util/issues/58

fix: fix spread(range) of react-deps

---

package.json
src/PortalWrapper.js

https://github.com/ant-design/ant-design/issues/19487

fix: portal wrapper getContainer 

---

README.md
src/switchScrollingEffect.js

Closes https://github.com/ant-design/ant-design/issues/19729

feat: switchScrollingEffect add a class when called

---

HISTORY.md

Ref: https://github.com/react-component/util/pull/65

doc: 4.16.1

---

src/hooks/useMergedState.ts
tests/hooks.test.js

fix https://github.com/ant-design/ant-design/issues/23553

fix: useMergedState not reset when value back to undefined

---

package.json

close https://github.com/react-component/animate/issues/99
close https://github.com/ant-design/ant-design/issues/24419

remove peerDependencies for react and react-dom

---

src/raf.ts
tests/raf.test.js

prepare for ant-design/ant-design#24495

add raf util

---

.eslintrc.js
src/ref.ts
tests/ref.test.js

ref https://github.com/ant-design/ant-design/pull/25328

fix: supportRef check memo

---

src/Children/toArray.ts
tests/toArray.test.js

ref https://github.com/ant-design/ant-design/issues/26420

feat: toArray support empty

---

src/Dom/scrollLocker.ts

Relate https://github.com/react-component/util/pull/179#issuecomment-751200232

fix: remove ScrollLocker touchmove

---

src/Dom/scrollLocker.ts
src/PortalWrapper.tsx
tests/scrollLocker.test.ts

Related https://github.com/ant-design/ant-design/pull/28687#issuecomment-754352917

fix: if ScrollLocker container change

---

src/Dom/scrollLocker.ts
tests/scrollLocker.test.ts

Related
https://github.com/ant-design/ant-design/pull/28687#issuecomment-754518269

improve: fix ScrollLocker clac scroll bar size

---

src/Dom/scrollLocker.ts
tests/scrollLocker.test.ts

Related
https://github.com/ant-design/ant-design/pull/28687#issuecomment-755248285

improve: replace ScrollLocker effect attr padding-right to width

---

.fatherrc.js
package.json

chore: add @babel/runtime

---

src/Dom/dynamicCSS.ts

fix https://github.com/ant-design/ant-design/issues/29864

fix: IE not support prepend

---

src/raf.ts
tests/raf.test.js

feat: raf support times

---

src/Dom/scrollLocker.ts

close https://github.com/ant-design/ant-design/issues/31303

fix: getContainer extra width style

---

src/Dom/dynamicCSS.ts
tests/dynamicCSS.test.tsx

ref https://github.com/ant-design/ant-design/pull/33890#issuecomment-1034493749

feat: dynamicCSS support customize mark

---

src/hooks/useState.ts
tests/hooks.test.js

ref https://github.com/ant-design/ant-design/issues/34316
很多地方都用到这个，干脆抽成一个 hook

feat: add safe setState

---

src/Dom/addEventListener.js

Use the same option as adding event listener to remove it

fix removeEventListener when using option

---

src/React/render.ts

服了，即便你给 dom patch 也会影响 React18 渲染。存到外面去……

fix: react 18 warning

---

src/React/render.ts

Reverts react-component/util#304
没用，revert 了

Revert "fix: react 18 warning"

---

examples/portal.tsx

Hi, my name is junior, my suggest is; "Remove anonymous function  from your code"
Have a nice day :+1:

Remove anonymous function

---

src/hooks/useMergedState.ts

refactor: fallback of useMergedState

---

src/Dom/findDOMNode.ts
tests/findDOMNode.test.tsx

ref https://github.com/react-component/tooltip/issues/444

feat: support isDOM

---

package.json
src/Dom/isVisible.ts

refactor: isVisible support IE11

---

src/hooks/useMobile.ts
tests/hooks.test.js

close https://github.com/ant-design/ant-design/issues/41321

fix: useMobile should not warn useLayoutEffect in SSR

---

src/utils/set.ts
tests/utils.test.js

ref https://github.com/ant-design/ant-design/pull/42604

feat: set support merge

---

package.json
src/utils/set.ts
tests/utils.test.js

fix https://github.com/ant-design/ant-design/issues/42742

fix: merge should support shallow copy

---

src/utils/set.ts
tests/utils.test.js

fix https://github.com/ant-design/ant-design/issues/42977

fix: ref should support copy

---

src/utils/get.ts
src/utils/set.ts
tests/utils.test.js

fix https://github.com/ant-design/ant-design/issues/43145

feat: set  support symbol

---

docs/examples/dynaymicCSS.tsx
src/Dom/dynamicCSS.ts
tests/dynamicCSS.test.tsx
tests/index.test.js

为 `@ant-design/cssinjs` 做准备，让 antd 样式始终在最上面。

feat: inject support priority

---

tests/hooks.test.js
tests/setStyle.test.ts

close https://github.com/react-component/util/security/code-scanning/2
close https://github.com/react-component/util/security/code-scanning/1

fix: code scanning alerts

---

.github/workflows/react-component-ci.yml

ref: https://github.com/codecov/codecov-action/issues/190

ci: fixed codecov warning

---

.github/workflows/react-component-ci.yml
tests/Portal.test.tsx
tests/react.test.tsx

test: rm legacy react-dom/test-utils

test: rm legacy react-dom/test-utils

---

package.json
src/ref.ts

chore: add @types/react-is

---

src/ref.ts
tests/ref.test.tsx

type: add type guard

---

src/ref.ts

chore: rewrite function => arrow function

chore: rewrite function => arrow function

---

src/omit.ts

perf: improve omit performance

---

.gitignore
package.json

chore: add @types/node

---

.github/workflows/react-component-ci.yml

https://github.com/ant-design/ant-design/issues/50387

test: use codecov/codecov-action
