src/PureRenderMixin.js
src/index.js
src/shallowEqual.js

Fixes webpack case error:
```
WARNING in ./~/rc-util/lib/shallowEqual.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
WARNING in ./~/rc-util/lib/shallowequal.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```
This error is wrong, but there's no reason for the module to exist anyway. This won't break backcompat.

Remove shallowEqual module, simply require 'shallowequal' directly

---

package.json
src/PureRenderMixin.js
tests/index.js

根据 https://github.com/ant-design/ant-design/issues/3338 的讨论，把 PureRenderMixin 加回来，然后去掉了里面的 warning。

Revert PureRenderMixin

---

.travis.yml
src/ref.ts
tests/ref.test.js

Too many place for compose ref since remove `findDOMNode` remove. Move the code into `rc-util` instead.

feat: Support `composeRef`

---

.gitignore
package.json
src/PortalWrapper.js
src/setStyle.ts
src/switchScrollingEffect.js
tests/setStyle.test.ts
tests/switchScrollingEffect.test.ts

Ref: 
https://github.com/react-component/drawer/issues/119
https://github.com/ant-design/ant-design/issues/19956

feat(PortaWrapper): add switchScrollingEffect func

---

README.md
src/switchScrollingEffect.js
tests/switchScrollingEffect.test.ts

Ref: https://github.com/react-component/dialog/pull/166#issuecomment-566006234

refactor: rename switch-scrolling-effect to ant-scrolling-effect

---

LICENSE
LICENSE.md
README.md
package.json

Fix all LICENSE warn. ✔️ ..

---

.fatherrc.js
package.json

看了一下，几个库 babel runtime 有 inline，有 deps 的。全改成 deps，也能省一些。

Dedup babel runtime

---

src/PortalWrapper.js

只在全局的情况下增加 openCount
https://github.com/ant-design/ant-design/issues/24821

fix https://github.com/ant-design/ant-design/issues/24821

---

src/ContainerRender.js
src/Portal.tsx
src/PortalWrapper.tsx
tests/Portal.test.tsx

refactor: Clean up unnecessary code

---

.eslintrc.js
src/PortalWrapper.tsx
tests/Portal.test.tsx

StrictMode 下 `constructor` 和 `getDerivedStateFromProps` 会多次执行，导致 `openCount` 数值错误。改造成了 `didMount` 和 `didUpdate` 不确定有没有坑。帮忙看下。
ref #https://github.com/ant-design/ant-design/issues/28228

fix: StrictMode modal scroll bar

---

src/omit.ts
tests/omit.test.ts

收拢 [omit.js](https://www.npmjs.com/package/omit.js) 到 `rc-util`，添加 TS 定义支持。

feat: Add omit

---

src/utils/set.ts
tests/utils.test.js

ref https://github.com/ant-design/ant-design/issues/29215
嵌套表单可以加一个 `preserve={false}` 支持。这样需要改造 `set` 让它遇到 `undefined` 时候不要 clone。

feat: set support remove

---

src/Dom/dynamicCSS.ts
tests/dynamicCSS.test.tsx

准备把注入相关的都收敛到 rc-util 里，去掉外部依赖。icons 还要加一下 csp 注入。
ref https://github.com/ant-design/ant-design/issues/29763

feat: Support csp inject

---

src/Dom/dynamicCSS.ts

On some browsers, especially Microsoft Edge Legacy, version 17.x spreading NodeList throws an error, because NodeList is not-iterable instance. Polyfills does not work.
Babel issue: https://github.com/babel/babel/issues/9993
Converting NodeList to an array: https://gomakethings.com/converting-a-nodelist-to-an-array-with-vanilla-javascript/
This pull request changes creating an `Array` from `NodeList` with `Array.from` instead of `spreading` to support as ancient browsers as IE6.
fix ant-design/ant-design#30234

Fix NodeList in some browsers (Invalid attempt to spread non-iterable instance.)

---

src/Dom/dynamicCSS.ts

fix: parentElement is null when the parent node is document-fragment

---

examples/getScrollBarSize.tsx
src/getScrollBarSize.tsx
tests/getScrollBarSize.test.ts

ref https://github.com/ant-design/ant-design/issues/30358

feat: Support target scrollbar size

---

.gitignore
examples/styleChecker.tsx
now.json
package.json
src/Dom/styleChecker.ts
tests/style.test.js

ref https://github.com/ant-design/ant-design/issues/31532

feat: Add style checker

---

src/hooks/useLayoutEffect.ts
src/isBrowserClient.ts
tests/hooks.test.js

把`rc-select`里的 `useLayoutEffect` 挪到`rc-util`。
Prepare for 
https://github.com/ant-design/ant-design/issues/30396
react-component/overflow#6
https://github.com/react-component/select/issues/614

feat: add useLayoutEffect hook

---

jest.config.js
package.json
tests/Portal.test.tsx
tests/hooks.test.js
tests/index.test.js
tests/ref.test.js
tests/setup.js
tests/toArray.test.js
tests/warning.test.js

test: Move all test case into React Testing Libary

---

src/Portal.tsx
tests/Portal.test.tsx

1. Auto restore container to the original place
2. ~~Add a `container` option, so that we can avoid creating a new container every time~~

fix: restore portal to dom

---

src/hooks/useId.ts
tests/hooks.test.js

根据当前环境自动切换 ID：
* 在 Test 下始终产出 mock id 以确保跨 React 版本 snapshot 唯一性
* 在 SSR 下根据 React 版本选择是否使用结构化 useId 还是 ssr-id 占位符，Client 端根据对应策略注水

feat: Support useId

---

package.json
src/Dom/dynamicCSS.ts
tests/dynamicCSS.test.tsx

qiankun 卸载 & 重新装载 时会创建新的 div，导致 cache 存在的真实 container 会过期。添加一个检测更新机制。

fix: qiankun remount app will create new container

---

src/omit.ts
tests/omit.test.ts

sync lodash

---

src/Dom/shadow.ts

fix: fallback ie

---

src/utils/set.ts
tests/utils.test.js

fix: list override

---

src/Dom/addEventListener.js

When target is nullish, it will throw `TypeError: Cannot read properties of null (reading 'addEventListener')`.
So I add the optional chaining to avoid the error.
@zombieJ

fix: addEventListenerWrap param target may be  nullish

---

src/Dom/shadow.ts
tests/shadow.test.tsx

close https://github.com/ant-design/ant-design/issues/43884

fix: dom not appended should not be treated as ShadowRoot

---

src/index.ts
src/ref.ts
tests/ref.test.js

`useComposeRef` 的 memo 逻辑写反了，导致用了它总是会重新刷新 ref。

fix: useComposeRef memo logic

---

src/hooks/useId.ts
tests/hooks-17.test.js
tests/hooks.test.js

拆分 `useId` 逻辑，如果是 React 18 则不需要调用 `useEffect` 进行更新。
ref https://github.com/ant-design/ant-design/issues/45296

perf: useId logic

---

src/raf.ts
tests/raf.test.js

这个错误会导致删除错误 id 导致 `cancel` 无法正确清理 raf。但是因为应用中有非常多的 raf，导致原生 id 会被迅速提升而不会遇到被误删的问题。

fix: raf.cancel not clean up correct map id

---

src/Dom/dynamicCSS.ts

`updateCSS` 在插入样式时会调用两遍 findStyles，由于中间不存在 dom 变化（或者可忽略），这里可以省去一半 `findStyles` 执行时间。

perf: avoid duplicated findStyles in updateCSS

---

src/ref.ts

Fixes the issue described in https://github.com/ant-design/ant-design/pull/44135
Why the issue exists:
The highlighted code in `rc-dropdown` returns `true` for react and `false` for preact
https://github.com/react-component/dropdown/blob/master/src/Overlay.tsx#L25
<details>
<summary>Screenshot</summary>
</details>
That's why the focus doesn't shift to the menu when using preact.
Now let's take a look at the `supportRef` code and add some console.log to it for debugging:
<details>
<summary>Screenshot</summary>
</details>
And here are the results:
<details>
<summary>react</summary>
</details>
<details>
<summary>preact</summary>
</details>
So, based on the screenshots above, we can conclude that in the case of preact, the `nodeOrComponent`  is a `function`, not an `object`, so the second …

Fix supportRef function for preact

---

docs/examples/getScrollBarSize.tsx
src/getScrollBarSize.tsx
tests/getScrollBarSize.test.ts

css 设置 `scrollbar-color` 后会导致 `::webkit-scrollbar` 伪类失效。测量仍然使用 `::webkit-scrollbar` 的数值导致滚动条宽度的计算错误。修复成实际测量值。

fix: scrollbar measure should consider `scrollbar-color` `::webkit-scrollbar` mixing

---

docs/examples/getScrollBarSize.tsx
src/getScrollBarSize.tsx

fix https://github.com/ant-design/ant-design/issues/47754
Chrome 下，`::-webkit-scrollbar` 设置 `width/height: atuo` 与 `style` 默认的 `width/height: atuo` 行为不一致。显式设置会变成固定占位，而默认 `auto` 则不会。
PS: JSDOM 不能模拟这种情况

fix: not force fill auto

---

src/Dom/findDOMNode.ts
src/proxyObject.ts
tests/findDOMNode.test.tsx
tests/proxyObject.test.ts

* 添加 `findDOMNode` 为 `nativeElement` 做支持，以允许在执行到 React 原生 `findDOMNode` 之前提前返回真实 DOM 节点（如果组件已经支持的话）。
* 添加 `proxyObject` 以支持在原 `ref` 已经被返回于原生 DOM 时，可以拓展返回 `nativeElement`

feat: Batch func to support React 18.3 findDOMNode

---

src/ref.ts
tests/ref.test.tsx

和 React 版本强绑定的，无论哪个优先在另一个版本里都会报 warning。根据版本做一下判断再使用。

feat: getNodeRef
